/**
 * Canonical RBAC role definitions (menu + route defaults).
 * Used by scripts/rbacSeed.js, GET /api/rbac/roles/:name, and login permission merge.
 */

// All menu keys as defined in menuAccessRoles
export const ALL_MENU_KEYS = [
  "dashboard",
  "adminUsers",
  "users",
  "courses",
  "bos",
  "dataMaintenance",
  "financialAuditing",
  "pcmDashboard",
  "tutorManagement",
  "directMeetManagement",
  "marketing",
  "vote",
  "userLandingPage",
  "tutorDashboard",
  "tutorsManagement",
  "documentVerification",
  "certificateMaintenance",
  "institutionalBoard",
  "notifications",
  "feedback",
];

// All route keys (subset of most common ones for Phase 1)
// In Phase 2, this becomes dynamic from a config file
export const ALL_ROUTE_KEYS = [
  "dashboard",
  "admin-users",
  "create-admin",
  "admin-details",
  "admin-analytics",
  "create-tutors",
  "tutor-details",
  "tutor-analytics",
  "tutor-list",
  "tutor-courses",
  "tutor-course-detail",
  "tutor-course-review",
  "tutor-payment-details",
  "users",
  "user-details",
  "courses",
  "add-course",
  "course-list",
  "edit-course",
  "bos",
  "bos-meetings",
  "bos-voting",
  "bos-proposals",
  "financial-auditing",
  "DM_Dashboard",
  "marketing-dashboard",
  "pcm-dashboard",
  "vote",
  "user-landing-page",
  "documentVerification",
  "Payment-record",
  "rbac-dashboard",
  "role-creation",
  "page-permissions",
];

// Role definitions with hierarchy and default permissions
export const roleDefinitions = [
  {
    roleName: "superadmin",
    displayName: "Super Admin",
    hierarchy: 100,
    menuAccess: ALL_MENU_KEYS.reduce((acc, key) => ({ ...acc, [key]: true }), {}),
    routeAccess: ALL_ROUTE_KEYS.reduce((acc, key) => ({ ...acc, [key]: true }), {}),
  },
  {
    roleName: "admin",
    displayName: "Admin",
    hierarchy: 90,
    menuAccess: ALL_MENU_KEYS.reduce((acc, key) => ({ ...acc, [key]: true }), {}),
    routeAccess: ALL_ROUTE_KEYS.reduce((acc, key) => ({ ...acc, [key]: true }), {}),
  },
  {
    roleName: "committeeoftrustees",
    displayName: "Committee of Trustees",
    hierarchy: 8,
    menuAccess: {
      dashboard: true,
      adminUsers: true,
      users: true,
      courses: true,
      bos: true,
      dataMaintenance: true,
      financialAuditing: true,
      pcmDashboard: true,
      tutorManagement: true,
      directMeetManagement: true,
      marketing: false,
      vote: true,
      userLandingPage: true,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: true,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      "admin-users": true,
      users: true,
      courses: true,
      bos: true,
      "financial-auditing": true,
      "DM_Dashboard": true,
      "pcm-dashboard": true,
      vote: true,
    },
  },
  {
    roleName: "boscontroller",
    displayName: "BOS Controller",
    hierarchy: 7,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: true,
      dataMaintenance: false,
      financialAuditing: false,
      pcmDashboard: true,
      tutorManagement: false,
      directMeetManagement: false,
      marketing: false,
      vote: true,
      userLandingPage: false,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      bos: true,
      "pcm-dashboard": true,
      vote: true,
    },
  },
  {
    roleName: "bosmembers",
    displayName: "BOS Members",
    hierarchy: 10,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: true,
      dataMaintenance: false,
      financialAuditing: false,
      pcmDashboard: true,
      tutorManagement: false,
      directMeetManagement: false,
      marketing: false,
      vote: true,
      userLandingPage: false,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      bos: true,
      "pcm-dashboard": true,
      vote: true,
    },
  },
  {
    roleName: "coursemanagement",
    displayName: "Course Management",
    hierarchy: 6,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: true,
      bos: false,
      dataMaintenance: false,
      financialAuditing: false,
      pcmDashboard: true,
      tutorManagement: false,
      directMeetManagement: true,
      marketing: false,
      vote: false,
      userLandingPage: false,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      courses: true,
      "add-course": true,
      "course-list": true,
      "edit-course": true,
      "DM_Dashboard": true,
      "pcm-dashboard": true,
    },
  },
  {
    roleName: "tutormanagement",
    displayName: "Tutor Management",
    hierarchy: 5,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: false,
      dataMaintenance: false,
      financialAuditing: false,
      pcmDashboard: false,
      tutorManagement: true,
      directMeetManagement: false,
      marketing: false,
      vote: false,
      userLandingPage: false,
      tutorDashboard: true,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      "create-tutors": true,
      "tutor-details": true,
      "tutor-list": true,
      "tutor-analytics": true,
      "tutor-courses": true,
      "tutor-course-detail": true,
      "tutor-course-review": true,
      "tutor-payment-details": true,
    },
  },
  {
    roleName: "usermanagement",
    displayName: "User Management",
    hierarchy: 4,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: true,
      courses: false,
      bos: false,
      dataMaintenance: true,
      financialAuditing: false,
      pcmDashboard: false,
      tutorManagement: false,
      directMeetManagement: true,
      marketing: false,
      vote: false,
      userLandingPage: true,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: true,
      institutionalBoard: false,
      notifications: true,
      feedback: true,
    },
    routeAccess: {
      dashboard: true,
      users: true,
      "user-details": true,
      "Payment-record": true,
    },
  },
  {
    roleName: "documentverification",
    displayName: "Document Verification",
    hierarchy: 3,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: false,
      dataMaintenance: false,
      financialAuditing: false,
      pcmDashboard: false,
      tutorManagement: false,
      directMeetManagement: false,
      marketing: false,
      vote: false,
      userLandingPage: false,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: true,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      documentVerification: true,
    },
  },
  {
    roleName: "financial",
    displayName: "Financial",
    hierarchy: 3,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: false,
      dataMaintenance: false,
      financialAuditing: true,
      pcmDashboard: false,
      tutorManagement: false,
      directMeetManagement: false,
      marketing: false,
      vote: false,
      userLandingPage: false,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      "financial-auditing": true,
    },
  },
  {
    roleName: "marketing",
    displayName: "Marketing",
    hierarchy: 2,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: false,
      dataMaintenance: false,
      financialAuditing: false,
      pcmDashboard: false,
      tutorManagement: false,
      directMeetManagement: false,
      marketing: true,
      vote: false,
      userLandingPage: true,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      "marketing-dashboard": true,
    },
  },
  {
    roleName: "auditor",
    displayName: "Auditor",
    hierarchy: 1,
    menuAccess: {
      dashboard: true,
      adminUsers: false,
      users: false,
      courses: false,
      bos: false,
      dataMaintenance: false,
      financialAuditing: true,
      pcmDashboard: false,
      tutorManagement: false,
      directMeetManagement: false,
      marketing: false,
      vote: false,
      userLandingPage: false,
      tutorDashboard: false,
      tutorsManagement: false,
      documentVerification: false,
      certificateMaintenance: false,
      institutionalBoard: false,
      notifications: true,
      feedback: false,
    },
    routeAccess: {
      dashboard: true,
      "financial-auditing": true,
      "Payment-record": true,
    },
  },
];

export function getRoleSeedDefinition(roleNameLower) {
  if (!roleNameLower || typeof roleNameLower !== "string") return null;
  return roleDefinitions.find((r) => r.roleName === roleNameLower.toLowerCase()) || null;
}

/** DB document overlays seed defaults (explicit keys in DB win, including false). */
export function mergePermissionMaps(seedDefaults, dbValue) {
  const base = seedDefaults && typeof seedDefaults === "object" ? { ...seedDefaults } : {};
  const db = dbValue && typeof dbValue === "object" ? dbValue : {};
  return { ...base, ...db };
}
